[template]
src = "okta-cert.tmpl"
dest = "/etc/apache2/mozilla/mellon/securitywiki.allizom.org.cert"
prefix = "/securitywiki-stage/stage"
keys = [
    "/config-okta"
]

reload_cmd = "/usr/sbin/apachectl graceful"
