okta-xml.toml
[template]
src = "okta-xml.tmpl"
dest = "/etc/apache2/mozilla/mellon/securitywiki.allizom.org.xml"
prefix = "/securitywiki-stage/stage"

keys = [
    "/config-okta"
]

reload_cmd = "/usr/sbin/apachectl graceful"
