[template]
src = "okta-idp.tmpl"
dest = "/etc/apache2/mellon/securitywiki.idp-metadata.xml"
prefix = "/%%STACK%%/%%ENVIRONMENT%%"

keys = [
    "/config/okta"
]

reload_cmd = "/usr/sbin/apachectl graceful"

