[template]
src = "okta-idp.tmpl"
dest = "/etc/apache2/mozilla/mellon/securitywiki.allizom.org.idp-metadata.xml"
prefix = "/securitywiki-stage/stage"

keys = [
    "/config-okta"
]

reload_cmd = "/usr/sbin/apachectl graceful"

